#!/bin/bash

# -- -- -- -- -- -- variables  -- -- -- -- -- -- #
REPO=""
BRANCH=""
CHANGE=""


# -- -- -- -- -- -- functions  -- -- -- -- -- -- #


# -- -- -- -- -- -- err check  -- -- -- -- -- -- #

(git status 2> /dev/null)

if (( $? )) ; then
  echo "Not a git repository"
  exit 1
fi


# -- -- -- -- -- -- teh logic  -- -- -- -- -- -- #


