#!/bin/bash
#[WIP]

# -- -- -- -- -- -- variables  -- -- -- -- -- -- #
REPO=""
BRANCH=""
CHANGE=""


# -- -- -- -- -- -- functions  -- -- -- -- -- -- #
function swallow_exec () {
  local COMMAND
  local OUTPUT
  local RETURN
  COMMAND="$1"
  OUTPUT="$($COMMAND 2>&1)"
  RETURN="$?"

  echo "$OUTPUT"
  return $RETURN
}


# -- -- -- -- -- -- err check  -- -- -- -- -- -- #
MSG="$(swallow_exec "git status")"
ERR="$?"
if (( $ERR )) ; then
  echo "$MSG"
  exit 1
fi


# -- -- -- -- -- -- teh logic  -- -- -- -- -- -- #


