#!/bin/bash

if [ "$#" -ne "3" ] ; then
  echo "Usage: $0 <search directory> <file regex pattern> <text regex pattern>"
  exit 0
fi

SEARCH_DIR="$1"
FILE_REGEX="$2"
TEXT_REGEX="$3"

function realpath () {
  while [ "$#" -gt "0" ] ; do
    TARGET="$1"
    FULLTARGET="$(cd "$(dirname "$TARGET")"; pwd -P)/$(basename "$TARGET")"
    if [ -n "$(echo "$TARGET" | grep -e '"' -e "'")" ] ; then
      echo "OMIT -- BAD FILENAME $FULLTARGET" >&2
    else
      echo -e "$FULLTARGET"
    fi
    shift
  done
}

function has_text() {
  FILE="$1"
  TEXT="$2"
  if [ -f "$FILE" ] ; then
    if [ -n "$(grep -i "$TEXT" "$FILE")" ] ; then
      echo "$FILE" >&2
      idea "$FILE"
    fi
  fi
} 

ALL_FILES="$(find "$SEARCH_DIR" -name "$FILE_REGEX")"

export -f has_text
realpath $ALL_FILES | xargs -I % bash -c 'has_text "'%'" "'"$TEXT_REGEX"'"'

