#!/bin/bash

if [ "$#" -ne "1" ] ; then
	echo "Usage: $0 <file to grab>"
    echo "'$0' puts the contents of the file into your clipboard using \`pbcopy\`"
	exit
fi

if [ -d "$1" ] ; then
    echo "Cannot grab a directory, silly ($1)"
    exit
fi

# FIXME
# this only works on macos, I need a linux compatible variant
cat "$1" | pbcopy
echo "Grabbed '$1'
