#!/bin/bash

SESSION="_user_$(head -c 9 /dev/urandom | base64 | sed 's:[+/]::g')"

OSA_SCRIPT=`cat << EOF
tell application "iTerm"
  tell current window
    tell current session of current tab
      set $SESSION to split vertically with default profile
    end tell
    tell $SESSION
      write text "$@"
    end tell
  end tell
end tell
EOF
`
echo "Executing '$@' in other pane"
osascript -e "$OSA_SCRIPT"
