#!/bin/bash

# because fuck the guys who maintain gnome-screenshot
# https://cialu.net/how-to-change-default-gnome-screenshot-savings-folder/
# https://bugzilla.gnome.org/show_bug.cgi?id=699642#c15

PREFIX="Screenshot-part"
TIME="$(date | sed -s 's/\s*//g')"
DIR=~/Pictures/linux-screenshots
FILE="${PREFIX}-${TIME}.png"
FLAGS="--area --file ${DIR}/${FILE}"

gnome-screenshot $FLAGS

