#!/bin/bash

# because fuck the guys who maintain gnome-screenshot
# https://cialu.net/how-to-change-default-gnome-screenshot-savings-folder/
# https://bugzilla.gnome.org/show_bug.cgi?id=699642#c15

FILE="0"
FLAG="--clipboard"
PREF=""

HERE="$( cd "$(dirname "$0")" ; pwd -P )"
EXEC=".screenshot_core"

$HERE/$EXEC "$FILE" "$FLAG" "$PREF"

