#!/bin/bash

################################################################################
# error checking

if [ "$#" -ne "2" ] ; then
	echo "Usage: $0 <songs_to_remove> <list_to_modify>"
	exit
fi

if [ -d "$1" ] ; then
    echo "Cannot strip from directory '$1'"
    exit 1
fi

if [ -d "$2" ] ; then
    echo "Cannot strip from directory '$2'"
    exit 1
fi


################################################################################
# variables

STAT_FUNC="playlistat"
if [ -z "`which \"$STAT_FUNC\"`" ] ; then

    THIS_DIR="`dirname \"$0\"`"
    TARG_FUNC="${THIS_DIR}/${STAT_FUNC}"

    if [ ! -f "$TARG_FUNC" ] ; then
        echo "Error: unable to find exec or function '$STRIP_FUNC'"
        exit 1
    fi

    STAT_FUNC="$TARG_FUNC"
fi

FILE="$2"
STRIP="$1"
STRIPPED="${FILE}_stripped"

################################################################################
# logic
# FIXME logic when used as part of another script
echo "Original `\"$STAT_FUNC\" \"$FILE\"`"
echo "Removing `\"$STAT_FUNC\" \"$STRIP\"`"

grep -v -f "${STRIP}" "${FILE}" > "${STRIPPED}"

# mv "${STRIPPED}" "${FILE}"
# echo "Final `\"$STAT_FUNC\" \"$FILE\"`"

